version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: blog
    ports:
      - 5432:5432
    volumes:
      - P:\docker-data\postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - '6379:6379'

  app:
    build:
      context: .
    restart: always
    ports:
      - '5000:5000'
    environment:
      NODE_ENV: production
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
