export const USER_REPOSITORY = 'USER_REPOSITORY';
export const BLOG_POST_REPOSITORY = 'BLOG_POST_REPOSITORY';
export const BLOG_POST_COMMENT_REPOSITORY = 'BLOG_POST_COMMENT_REPOSITORY';

export const MAIL_JOB = 'MAIL_JOB';
export const MAIL_QUEUE = 'MAIL_QUEUE';
